# Databricks Apps Configuration
# This app reads from Lakebase Postgres (synced from UC: pubsec_geo_law.demo)

command:
  - "bash"
  - "-c"
  - |
    # Install deps + build frontend + start backend with constrained heap
    npm install && npm run build:clean && npm install --prefix backend
    exec node --max-old-space-size=1536 backend/server.js

env:
  # Server configuration
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8000"
  # Increase Node.js heap — env var is the most reliable way
  - name: NODE_OPTIONS
    value: "--max-old-space-size=1536"
  
  # Postgres schema where synced tables are located
  - name: POSTGRES_SCHEMA
    value: "demo"
  
  # Databricks Unity Catalog configuration (retained for agent / AI features)
  # DATABRICKS_HOST is auto-injected by the platform — do NOT set it here
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/288a7ec183eea397"
  - name: DATABRICKS_CATALOG
    value: "pubsec_geo_law"
  - name: DATABRICKS_SCHEMA
    value: "demo"
  
  # Agent configuration
  - name: DATABRICKS_AGENT_ENDPOINT
    value: "databricks-gpt-5-2"
  
  # Databricks Apps automatically injects DATABRICKS_TOKEN for the app's service principal
  # PGHOST, PGPORT, PGDATABASE, PGUSER, PGSSLMODE are auto-injected when
  # a database resource is attached below.

resources:
  # Compute allocation
  # Note: Databricks Apps use compute_size (set in UI), not raw memory/cpu
  
  # Declare resources the app needs access to
  # This grants the app's service principal permission to use these resources
  
  # Lakebase Postgres database (primary data source)
  database:
    - name: lakebase-db
      database_instance_name: "investigative-analytics-pg"
      database_name: "investigative_analytics"
      permission: CAN_CONNECT_AND_CREATE

  # SQL Warehouse (retained for agent / AI model serving queries)
  sql_warehouse:
    - name: sql-warehouse
      id: "288a7ec183eea397"
      permission: CAN_USE
  
  serving_endpoint:
    - name: agent-endpoint
      endpoint_name: "databricks-gpt-5-2"
      permission: CAN_QUERY

