command: ["npm", "run", "start"]

source:
  git:
    url: "https://github.com/will-yuponce-db/graph-crime-detection.git"
    branch: "main"

env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "8000"
  - name: VITE_FORCE_OPTIMIZE_DEPS
    value: "true"

